# Script made by DragGon7601 on 12 June 2016

mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:0>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:1>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:2>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:3>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:4>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:5>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:6>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:7>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:8>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:9>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:10>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:11>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:12>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:13>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:14>, "terra 1, metallum 2, permutatio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_copper:15>, "terra 1, metallum 2, permutatio 1");

mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:0>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:1>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:2>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:3>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:4>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:5>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:6>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:7>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:8>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:9>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:10>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:11>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:12>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:13>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:14>, "lucrum 3, terra 1, vitreus 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_diamond:15>, "lucrum 3, terra 1, vitreus 3");

mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:0>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:1>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:2>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:3>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:4>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:5>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:6>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:7>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:8>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:9>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:10>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:11>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:12>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:13>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:14>, "lucrum 1, metallum 2, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_gold:15>, "lucrum 1, metallum 2, terra 1");

mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:0>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:1>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:2>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:3>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:4>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:5>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:6>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:7>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:8>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:9>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:10>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:11>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:12>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:13>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:14>, "terra 1, metallum 3");
mods.thaumcraft.Aspects.set(<HarderOres:ore_iron:15>, "terra 1, metallum 3");

mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:0>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:1>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:2>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:3>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:4>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:5>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:6>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:7>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:8>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:9>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:10>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:11>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:12>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:13>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:14>, "metallum 3, ordo 1, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_lead:15>, "metallum 3, ordo 1, perditio 1");

mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:0>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:1>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:2>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:3>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:4>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:5>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:6>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:7>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:8>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:9>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:10>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:11>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:12>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:13>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:14>, "metallum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_nickel:15>, "metallum 1");

//WTF Some of the normal nickel ores dont have aspects? Lets fix that while we are at it.
mods.thaumcraft.Aspects.set(<GalaxySpace:mercuryblocks:5>, "metallum 1");
mods.thaumcraft.Aspects.set(<ImmersiveEngineering:ore:4>, "metallum 1");

mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:0>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:1>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:2>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:3>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:4>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:5>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:6>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:7>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:8>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:9>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:10>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:11>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:12>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:13>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:14>, "machina 2, potentia 3, terra 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_redstone:15>, "machina 2, potentia 3, terra 1");

mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:0>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:1>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:2>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:3>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:4>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:5>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:6>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:7>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:8>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:9>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:10>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:11>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:12>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:13>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:14>, "lucrum 1, metallum 3, perditio 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_silver:15>, "lucrum 1, metallum 3, perditio 1");

mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:0>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:1>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:2>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:3>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:4>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:5>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:6>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:7>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:8>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:9>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:10>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:11>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:12>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:13>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:14>, "metallum 3, perditio 1, vitreus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_tin:15>, "metallum 3, perditio 1, vitreus 1");

//HarderOres gives Aluminum a fancy name.
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:0>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:1>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:2>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:3>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:4>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:5>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:6>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:7>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:8>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:9>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:10>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:11>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:12>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:13>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:14>, "metallum 3, aer 1, motus 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_bauxite:15>, "metallum 3, aer 1, motus 1");

//Again I'm Fixing the other ores while I'm at it. (Aluminum ore blocks fyi)
mods.thaumcraft.Aspects.set(<ElectriCraft:electricraft_block_ore:4>, "metallum 3, aer 1, motus 1");

//Iron that spawns under rivers. I added aqua because of this.
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:0>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:1>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:2>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:3>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:4>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:5>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:6>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:7>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:8>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:9>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:10>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:11>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:12>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:13>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:14>, "terra 1, metallum 3, aqua 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_limonite:15>, "terra 1, metallum 3, aqua 1");

mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:0>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:1>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:2>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:3>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:4>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:5>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:6>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:7>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:8>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:9>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:10>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:11>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:12>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:13>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:14>, "lucrum 2, potentia 2, venenum 1");
mods.thaumcraft.Aspects.set(<HarderOres:ore_uranium:15>, "lucrum 2, potentia 2, venenum 1");
