#Tweak chest loot so its not so uber
val ironScrap = <RotaryCraft:rotarycraft_item_shaftcraft:10>;
val ak47 = <flansmod:ak47>;
val ak47Ammo = <flansmod:ak47Ammo>;
val barret = <flansmod:barrett>;
val barrettAmmo = <flansmod:barrettAmmo>;
val barrettExplosiveAmmo = <flansmod:barrettExplosiveAmmo>;
val goldDesertEagle = <flansmod:goldDesertEagle>;
val desertEagle = <flansmod:desertEagle>;
val desertEagleAmmo = <flansmod:desertEagleAmmo>;
val fnscar = <flansmod:fnscar>;
val fnscarAmmo = <flansmod:fnscarAmmo>;
val glock = <flansmod:glock>;
val glockAmmo = <flansmod:glockAmmo>;
val m1014 = <flansmod:m1014>;
val m1014Ammo = <flansmod:m1014Ammo>;
val m16a4 = <flansmod:m16a4>;
val m16a4Ammo = <flansmod:m16a4Ammo>;
val m249 = <flansmod:m249>;
val m249Ammo = <flansmod:m249Ammo>;
val m60 = <flansmod:m60>;
val m60Ammo = <flansmod:m60Ammo>;
val m72law = <flansmod:m72law>;
val m72lawAmmo = <flansmod:m72lawAmmo>;
val m9 = <flansmod:m9>;
val m9Ammo = <flansmod:m9Ammo>;
val minigun = <flansmod:minigun>;
val minigunAmmo = <flansmod:minigunAmmo>;
val minigunExplosiveAmmo = <flansmod:minigunExplosiveAmmo>;
val mp5 = <flansmod:mp5>;
val mp5Ammo = <flansmod:mp5Ammo>;
val p90 = <flansmod:p90>;
val p90Ammo = <flansmod:p90Ammo>;
val r870 = <flansmod:r870>;
val r870Ammo = <flansmod:r870Ammo>;
val stinger = <flansmod:stinger>;
val stingerAmmo = <flansmod:stingerAmmo>;
val fragment = <ChromatiCraft:chromaticraft_item_fragment>;

vanilla.loot.removeChestLoot("dungeonChest", ironScrap);
vanilla.loot.addChestLoot("dungeonChest", <ChromatiCraft:chromaticraft_item_fragment>.weight(50),1,1);
vanilla.loot.addChestLoot("dungeonChest", <ChromatiCraft:chromaticraft_item_fragment>.weight(50),1,1);
vanilla.loot.addChestLoot("dungeonChest", ironScrap.weight(10),1,5);
vanilla.loot.addChestLoot("dungeonChest", ironScrap.weight(10),1,5);
vanilla.loot.addChestLoot("dungeonChest", ak47.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", barret.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", goldDesertEagle.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", desertEagle.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", fnscar.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", glock.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", m1014.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", m16a4.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", m249.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", m60.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", m72law.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", m9.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", minigun.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", mp5.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", p90.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", r870.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", stinger.weight(5),1,1);
vanilla.loot.addChestLoot("dungeonChest", ak47Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("dungeonChest", barrettAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("dungeonChest", barrettExplosiveAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("dungeonChest", desertEagleAmmo.weight(7),1,4);
vanilla.loot.addChestLoot("dungeonChest", fnscarAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("dungeonChest", glockAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("dungeonChest", m1014Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("dungeonChest", m16a4Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("dungeonChest", m249Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("dungeonChest", m60Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("dungeonChest", m72lawAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("dungeonChest", m9Ammo.weight(7),1,5);
vanilla.loot.addChestLoot("dungeonChest", minigunAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("dungeonChest", minigunExplosiveAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("dungeonChest", mp5Ammo.weight(7),1,4);
vanilla.loot.addChestLoot("dungeonChest", p90Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("dungeonChest", r870Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("dungeonChest", stingerAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("dungeonChest", fragment.weight(10),1,1);

vanilla.loot.removeChestLoot("mineshaftCorridor", ironScrap);
vanilla.loot.addChestLoot("mineshaftCorridor", <ChromatiCraft:chromaticraft_item_fragment>.weight(50),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", <ChromatiCraft:chromaticraft_item_fragment>.weight(50),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", ironScrap.weight(10),1,5);
vanilla.loot.addChestLoot("mineshaftCorridor", ironScrap.weight(10),1,5);
vanilla.loot.addChestLoot("mineshaftCorridor", ak47.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", barret.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", goldDesertEagle.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", desertEagle.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", fnscar.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", glock.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", m1014.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", m16a4.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", m249.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", m60.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", m72law.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", m9.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", minigun.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", mp5.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", p90.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", r870.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", stinger.weight(5),1,1);
vanilla.loot.addChestLoot("mineshaftCorridor", ak47Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("mineshaftCorridor", barrettAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("mineshaftCorridor", barrettExplosiveAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("mineshaftCorridor", desertEagleAmmo.weight(7),1,4);
vanilla.loot.addChestLoot("mineshaftCorridor", fnscarAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("mineshaftCorridor", glockAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("mineshaftCorridor", m1014Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("mineshaftCorridor", m16a4Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("mineshaftCorridor", m249Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("mineshaftCorridor", m60Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("mineshaftCorridor", m72lawAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("mineshaftCorridor", m9Ammo.weight(7),1,5);
vanilla.loot.addChestLoot("mineshaftCorridor", minigunAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("mineshaftCorridor", minigunExplosiveAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("mineshaftCorridor", mp5Ammo.weight(7),1,4);
vanilla.loot.addChestLoot("mineshaftCorridor", p90Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("mineshaftCorridor", r870Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("mineshaftCorridor", stingerAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("mineshaftCorridor", fragment.weight(10),1,1);

vanilla.loot.removeChestLoot("strongholdCorridor", ironScrap);
vanilla.loot.addChestLoot("strongholdCorridor", <ChromatiCraft:chromaticraft_item_fragment>.weight(50),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", ironScrap.weight(10),1,5);
vanilla.loot.addChestLoot("strongholdCorridor", ironScrap.weight(10),1,5);
vanilla.loot.addChestLoot("strongholdCorridor", ak47.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", barret.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", goldDesertEagle.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", desertEagle.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", fnscar.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", glock.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", m1014.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", m16a4.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", m249.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", m60.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", m72law.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", m9.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", minigun.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", mp5.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", p90.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", r870.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", stinger.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCorridor", ak47Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCorridor", barrettAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("strongholdCorridor", barrettExplosiveAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("strongholdCorridor", desertEagleAmmo.weight(7),1,4);
vanilla.loot.addChestLoot("strongholdCorridor", fnscarAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCorridor", glockAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCorridor", m1014Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCorridor", m16a4Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCorridor", m249Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCorridor", m60Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCorridor", m72lawAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("strongholdCorridor", m9Ammo.weight(7),1,5);
vanilla.loot.addChestLoot("strongholdCorridor", minigunAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCorridor", minigunExplosiveAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCorridor", mp5Ammo.weight(7),1,4);
vanilla.loot.addChestLoot("strongholdCorridor", p90Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCorridor", r870Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCorridor", stingerAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("strongholdCorridor", fragment.weight(10),1,1);

vanilla.loot.removeChestLoot("strongholdCrossing", ironScrap);
vanilla.loot.addChestLoot("strongholdCrossing", <ChromatiCraft:chromaticraft_item_fragment>.weight(50),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", ironScrap.weight(10),1,5);
vanilla.loot.addChestLoot("strongholdCrossing", ironScrap.weight(10),1,5);
vanilla.loot.addChestLoot("strongholdCrossing", ak47.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", barret.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", goldDesertEagle.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", desertEagle.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", fnscar.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", glock.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", m1014.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", m16a4.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", m249.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", m60.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", m72law.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", m9.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", minigun.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", mp5.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", p90.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", r870.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", stinger.weight(5),1,1);
vanilla.loot.addChestLoot("strongholdCrossing", ak47Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCrossing", barrettAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("strongholdCrossing", barrettExplosiveAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("strongholdCrossing", desertEagleAmmo.weight(7),1,4);
vanilla.loot.addChestLoot("strongholdCrossing", fnscarAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCrossing", glockAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCrossing", m1014Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCrossing", m16a4Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCrossing", m249Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCrossing", m60Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCrossing", m72lawAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("strongholdCrossing", m9Ammo.weight(7),1,5);
vanilla.loot.addChestLoot("strongholdCrossing", minigunAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCrossing", minigunExplosiveAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCrossing", mp5Ammo.weight(7),1,4);
vanilla.loot.addChestLoot("strongholdCrossing", p90Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCrossing", r870Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("strongholdCrossing", stingerAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("strongholdCrossing", fragment.weight(10),1,1);

vanilla.loot.removeChestLoot("villageBlacksmith", ironScrap);
vanilla.loot.addChestLoot("villageBlacksmith", <ChromatiCraft:chromaticraft_item_fragment>.weight(50),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", <ChromatiCraft:chromaticraft_item_fragment>.weight(50),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", ironScrap.weight(10),1,5);
vanilla.loot.addChestLoot("villageBlacksmith", ak47.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", barret.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", goldDesertEagle.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", desertEagle.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", fnscar.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", glock.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", m1014.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", m16a4.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", m249.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", m60.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", m72law.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", m9.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", minigun.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", mp5.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", p90.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", r870.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", stinger.weight(5),1,1);
vanilla.loot.addChestLoot("villageBlacksmith", ak47Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("villageBlacksmith", barrettAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("villageBlacksmith", barrettExplosiveAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("villageBlacksmith", desertEagleAmmo.weight(7),1,4);
vanilla.loot.addChestLoot("villageBlacksmith", fnscarAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("villageBlacksmith", glockAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("villageBlacksmith", m1014Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("villageBlacksmith", m16a4Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("villageBlacksmith", m249Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("villageBlacksmith", m60Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("villageBlacksmith", m72lawAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("villageBlacksmith", m9Ammo.weight(7),1,5);
vanilla.loot.addChestLoot("villageBlacksmith", minigunAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("villageBlacksmith", minigunExplosiveAmmo.weight(7),1,3);
vanilla.loot.addChestLoot("villageBlacksmith", mp5Ammo.weight(7),1,4);
vanilla.loot.addChestLoot("villageBlacksmith", p90Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("villageBlacksmith", r870Ammo.weight(7),1,3);
vanilla.loot.addChestLoot("villageBlacksmith", stingerAmmo.weight(7),1,2);
vanilla.loot.addChestLoot("villageBlacksmith", fragment.weight(10),1,1);
